name: restclient

services:

  app:
    scanner: false
    api: 3
    type: lando
    build_as_root:
      - apt-get update -y && apt-get install -y libxrender1 libxtst6 libxi6 --no-install-recommends && rm -rf /var/lib/apt/lists/*
    services:      
      image: eclipse-temurin:8u402-b06-jre-jammy
      command: 'tail -f /dev/null'
      
      # Uncomment these 2 lines if you need to access the built-in Trace Server on your computer at address 0.0.0.0:10101
      #ports:
      #  - '10101:10101'
      
      # https://medium.com/@sahilgulghane22/running-gui-applications-in-docker-containers-9c36c3196a6b
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        # App settings files folder.
        - ./rest-client:/var/www/.rest-client
      environment:
        DISPLAY: ":0"
    volumes:
      app:

tooling:
  java:
    service: app
  restclient:
    service: app
    cmd:
      - java -jar restclient-ui-fat-3.7.1.jar
  restclient-cli:
    service: app
    cmd:
      - java -jar restclient-cli-fat-3.7.1.jar

