name: restclient

services:

  app:
    scanner: false
    api: 3
    type: lando
    services:      
      image: kaszarobert/restclient_docker:latest
      command: 'tail -f /dev/null'
      
      # Uncomment these 2 lines if you need to access the built-in Trace Server on your computer at address 0.0.0.0:10101
      #ports:
      #  - '10101:10101'
      
      # https://medium.com/@sahilgulghane22/running-gui-applications-in-docker-containers-9c36c3196a6b
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        # App settings files folder.
        #- ./rest-client:/var/www/.rest-client
      environment:
        DISPLAY: $DISPLAY
    volumes:
      app:

tooling:
  java:
    service: app
    user: newuser
  restclient:
    service: app
    user: newuser
    cmd:
      - java -jar /application/restclient-ui.jar
  restclient-cli:
    service: app
    user: newuser
    cmd:
      - java -jar /application/restclient-cli.jar

